### ISSUE TITLE
Have bug at on-screen help

### ISSUE THREAD

**Issue by Midas086** [Nacurutu/ARC-S-Theme-Remix---The-RA-CFW#3]
Your theme is very beautiful and I really like it. But there is a bug with on-screen help on the R36S device. Could you please fix it in the next update?
And could you please move the battery to the left corner because it's in the same position as a clock.
Thank you and have a nice day.
![IMG_0393](https://github.com/Nacurutu/es-theme-ARC-S-Theme-Remix---The-RA-CFW/assets/157221301/85d5684d-d081-4e3a-8ede-f21463e93814)

**Comment by Midas086** [comment]
By the way, it would be nice to have an option to make the font in the menu larger. Thank youBy the way, it would be nice to have an option to make the font in the menu larger. Thank you

**Comment by Nacurutu** [comment]
> By the way, it would be nice to have an option to make the font in the menu larger. Thank youBy the way, it would be nice to have an option to make the font in the menu larger. Thank you

Hi, The Theme was made with the THE RA CFW for ARC OS in mind... at the moment, the theme works properly on the ARC.. as I don't have more devices, I'm not able to make changes to support your handheld, however, if u want, you can fork the repository and make the changes to fit ur device, OS and ES version.

Also, thank you for ur kind words regarding the theme!
